#!/bin/bash
# User-inputted values for new Linode
# <UDF name="user_hostname" Label="Hostname for new Linode" />
# <UDF name="user_username" Label="Username for non-root account" />
# <UDF name="user_password" Label="Password for new user" />
# <UDF name="site_name" Label="Virtual Host Name" />
source <ssinclude StackScriptID="1">
exec >>/home/rootlog.txt 2>&1
#---- Update apt
system_update
# install failtoban
apt-get -y install fail2ban
#install apache2
apt-get install -y apache2
cp /etc/apache2/apache2.conf /etc/apache2/apache2.backup.conf
sed -i 's/KeepAlive Off/KeepAlive On/' /etc/apache2/apache2.conf
apt-get install -y mysql-server
adduser --disabled-password --gecos "" --shell /bin/bash ed
usermod -aG www-data ed
usermod -aG sudo ed
usermod -g www-data ed
apt install software-properties-common -y
add-apt-repository ppa:ondrej/php -y
apt-get update
apt-get install -y php5.6 php5.6-mysql php5.6-bcmath php5.6-curl php5.6-gd php5.6-mbstring php5.6-json php5.6-xml php5.6-xmlrpc php5.6-zip
# do basic apache stuff
echo "fixing basic required apache mods"
a2enmod headers
a2enmod rewrite
a2dismod mpm_event
a2enmod mpm_prefork
systemctl reload apache2
#install drush
wget https://github.com/drush-ops/drush/releases/download/8.3.0/drush.phar
php drush.phar core-status
chmod +x drush.phar
mv drush.phar /usr/local/bin/drush
# fix UFW settings
ufw default allow outgoing
ufw default deny incoming
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
ufw status
#---- Virtual hosts
if [ ! -n "$SITE_NAME" ]; then
    mkdir -p /var/www/nogo
else
    a2dissite default
    mkdir -p /var/www/sites/$SITE_NAME
    cat > /etc/apache2/sites-available/$SITE_NAME.conf << EOF
        <VirtualHost *:80>
            ServerName  $SITE_NAME
            DirectoryIndex index.html index.php
            DocumentRoot /var/www/sites/$SITE_NAME
            LogLevel warn
            ErrorLog  /var/log/$SITE_NAME-error.log
            CustomLog /var/log/$SITE_NAME-access.log combined
        </VirtualHost>
EOF
    a2ensite $SITE_NAME.conf
    systemctl reload apache2
fi
chown -R $USER_USERNAME:www-data /var/www/sites/

