#!/bin/bash

# Update and upgrade the OS

sudo apt update && sudo apt upgrade

# Script variables

hostname=yourhostname
fqdn=yourfqdn
ipaddress=xxx.xxx.xxx.xxx
user=youruser

# Set the hostname

hostnamectl set-hostname $hostname
echo "$ipaddress $fqdn" >> /etc/hosts

# Add a new user non-interactively. Set a password when the system is up and you are logged in.

adduser --disabled-password --gecos "" $user

# configure basic UFW settings

ufw default allow outgoing
ufw default deny incoming
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable

# Install fail2ban

apt-get install fail2ban

# Create custom configurable config files

cp /etc/fail2ban/fail2ban.conf /etc/fail2ban/fail2ban.local
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

# Install Nginx

apt install nginx

# Install PHP, PHP-FPM and extensions required for Drupal 8.x

apt install php-fpm -y

apt install php-date php-dom php-gd php-json php-pdo php-mysql php-mysql php-xml -y

# Install MySql Server

apt install mysql-server

# Install Drush using Composer

apt install unzip
cd ~
curl -sS https://getcomposer.org/installer -o composer-setup.php
HASH=`curl -sS https://composer.github.io/installer.sig`
php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --install-dir=/usr/local/bin --filename=composer

# NB Finish the installation as non-root user - 'composer global require drush/drush && export PATH="$HOME/.composer/vendor/drush/drush:$PATH"'

